spring:
  datasource:
#    url: jdbc:postgresql://database:5432/postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: pgsql
    password: qwerty1234
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
  jpa:
    properties:
      hibernate:
        ddl-auto: none
        temp:
          use_jdbc_metadata_defaults: false
    generate-ddl: true
  mail:
    host: smtp.mail.ru
    username: transport_fake@mail.ru
    password: itiswatching
    port: 465
    protocol: smtps


logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.web: WARN
    org.springframework.security: DEBUG
    org.ncstudy: DEBUG

server:
  port: 8901  # for testing without docker

config:
  signing-key: MaYzkSjmkzPC57L
  security-realm: Transport Eye is watching